// تسميات عربية مختصرة لأنواع أخطاء محرك التدقيق
export const ERROR_LABELS: Record<string, string> = {
  SUBJECT_EMPTY: "عنوان فارغ",
  SUBJECT_CUSTOM_UNCONFIRMED: "عنوان مخصص غير مؤكد",
  DEPARTMENT_MISSING: "جهة غير مختارة",
  DEPARTMENT_INACTIVE: "جهة غير فعالة",
  COMPANY_MISSING: "شركة غير مختارة",
  COMPANY_INACTIVE: "شركة غير فعالة",
  ROUTE_MISSING: "مسار غير مختار",
  ROUTE_INACTIVE: "مسار غير فعال",
  ROUTE_PRODUCT_MISMATCH: "منتج لا يطابق المسار",
  SOURCE_ROUTE_MISMATCH: "مصدر تجهيز لا يطابق المسار",
  DRIVERS_EMPTY: "جدول سائقين فارغ",
  VEHICLE_DUPLICATE: "رقم سيارة مكرر",
  SEQUENCE_DUPLICATE: "تسلسل مكرر",
  SEQUENCE_GAP: "تسلسل ناقص",
  VEHICLE_COUNT_MISMATCH: "عدد السيارات لا يطابق الجدول",
  CUT_FORMS_MISSING: "استمارات قطع غير مربوطة",
  CUT_FORM_DUPLICATE: "استمارة قطع مكررة",
  CUT_FORM_NO_DATE: "استمارة بلا تاريخ",
  CUT_FORM_NO_QUANTITY: "استمارة بلا كمية",
  LOADED_GT_CUT: "مجهزة أكبر من المقطوعة",
  REMAINING_MISMATCH: "متبقية غير مطابقة",
  REMAINING_NEGATIVE: "متبقية سالبة",
  CUT_FORM_NO_SOURCE: "استمارة بلا مصدر تجهيز",
  CUT_FORM_CLOSED: "استمارة مغلقة/منتهية",
  CUT_FORM_REUSED: "استمارة مستخدمة سابقاً",
  CUT_FORM_NOT_ATTACHED: "استمارة غير مرفقة",
  CONTRACT_MISSING: "عقد غير مربوط",
  TAX_LETTER_MISSING: "كتاب ضريبة غير مربوط",
  TAX_CONTRACT_MISMATCH: "ضريبة لا تطابق العقد",
  QUANTITY_EXCEEDS_ALLOWED: "كمية تتجاوز المسموح",
  CUT_EXCEEDS_ALLOWED: "مقطوعة تتجاوز المسموح",
  PREVIOUS_BOOK_MISSING: "كتاب سابق غير مدخل",
  PREVIOUS_BOOK_NO_DATE: "كتاب سابق بلا تاريخ",
  REQUIRED_ATTACHMENT_MISSING: "مرفق إلزامي ناقص",
  ATTACHMENT_NO_FILE: "مرفق بلا ملف",
  ATTACHMENT_NOT_VERIFIED: "مرفق غير مدقق",
  ATTACHMENT_NO_TITLE: "مرفق بلا وصف",
  DRIVERS_TABLE_NOT_UPLOADED: "جدول سائقين غير مرفوع",
};
